[[cluster]]
name = "cron"
failure_count = 1
task_threshold = 40
aws_region = "ap-northeast-1"
aws_profile = "prod"
incoming_webhook = "https://hooks.slack.com/services/xxxxxx"

### 0 is ignore check
[[cluster.task]]
name = "hoge"
times = 0

[[cluster.task]]
name = "fuga"
times = 2